system:
  language: yo

models:
  gpt4_text: text-davinci-003
  whisper: base
  asr: chrisjay/fonxlsr
  tts_fon: facebook/mms-tts-fon
  tts_yor: facebook/mms-tts-yor
  gpt4_chat: gpt-4o
  nllb: facebook/nllb-200-distilled-600M

transcription:
  type: whisper

translation:
  type: google

features:
  use_rag: False